# Generated by Django 3.2.6 on 2021-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Doing'), (2, 'Done')], default=0)),
            ],
        ),
    ]
